[package]
name = "enfys-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
crossbeam = "0.8.4"
ws = { version = "0.9.2", default-features = false }

[dev-dependencies]
mio = "*"
url = "*"
